values: &values
  app_name: panchew
  tropo:
    app_id: 52432
    app_phone: 4086416746
    api_url: http://api.tropo.com
    token: 298a1c2b0c55144bb7ceef35dc1da032d18e86af26eb6bd81ca1b3113ee8725202ae7864f150060807a3d0ac

development: &development
  <<: *values

test: &test
  <<: *values

production: &production
  <<: *values
